
#
# Optional Volumes:
#  - /opt/phabricator/conf - configuration
#  - /var/repo - code repos
#
#
phabricator:
    build: .
    links: ['database']
    ports: ['8000:80']


database:
    build: database/
